const TransactionHeaderSchema = {
  name: 'TransactionHeader',
  primaryKey: 'id_transaksi',
  properties: {
    id_transaksi: 'string',
    pelanggan: 'Customer',
    tanggal: 'string',
    pilihan_pembayaran: 'string?',
    metode_pembayaran: 'string?',
    diskon: {type: 'int', default: 0},
    pajak: {type: 'int', default: 0},
    ongkir: {type: 'int', default: 0},
    jlh_pembayaran: {type: 'int', default: 0},
    bayar: {type: 'int', default: 0},
    kembali: {type: 'int', default: 0},
    total_belanja: {type: 'int', default: 0},
    pembayaran: {type: 'int', default: 0},
    sisa_pembayaran: {type: 'int', default: 0},
    jatuh_tempo: 'string?',
    detail: 'TransactionDetail[]',
    status: 'string',
    terkirim: {type: 'int', default: 0},
    draft: {type: 'int', default: 0},
    bank_tujuan: 'string?',
    bank_pengirim: 'string?',
    nama_pemilik: 'string?',
    nomor_rekening: 'string?',
    mesin_edc: 'string?',
    nama_bank: 'string?',
    nomor_kartu: 'string?',
  },
};

export default TransactionHeaderSchema;
